// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/images": {
            "post": {
                "security": [
                    {
                        "X-Profile-ID": []
                    }
                ],
                "description": "Allows to upload from 1 to 10 images in one request. Supported formats: JPEG, PNG, GIF. Maximum size of a single file: 20 MB.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Images"
                ],
                "summary": "Upload images",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User profile UUID (v4 format)",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image files to download",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "All images have been uploaded successfully",
                        "schema": {
                            "$ref": "#/definitions/images_upload.Response"
                        }
                    },
                    "207": {
                        "description": "Some of the images were uploaded successfully, some with errors",
                        "schema": {
                            "$ref": "#/definitions/images_upload.PartialSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error: missing header, invalid UUID, no files, too many files",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "422": {
                        "description": "None of the images could be processed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/images/info": {
            "get": {
                "security": [
                    {
                        "X-Profile-ID": []
                    }
                ],
                "description": "Retrieves info for images by their IDs. Max number of image IDs per request: 200",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Images"
                ],
                "summary": "Get images info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User profile UUID (v4 format)",
                        "name": "X-Profile-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Array of image IDs to fetch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/images_info.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success with empty array (no images found)",
                        "schema": {
                            "$ref": "#/definitions/images_info.Response"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid JSON, no image IDs provided, all IDs are invalid, or too many IDs requested",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error - database query failed",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "image.FailedImageResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                }
            }
        },
        "image.Image": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "image_id": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "images_info.Request": {
            "type": "object",
            "properties": {
                "image_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "images_info.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.Image"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "images_upload.PartialSuccessResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "failed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.FailedImageResponse"
                    }
                },
                "failed_count": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.Image"
                    }
                },
                "status": {
                    "type": "string"
                },
                "success_count": {
                    "type": "integer"
                }
            }
        },
        "images_upload.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image.Image"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "\"Image operations: uploading and receiving information\"",
            "name": "Images"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Image Service API",
	Description:      "Microservice for downloading, receiving information and storing images",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
